# Generated by Django 3.0.6 on 2020-05-27 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='zipcode',
            new_name='phonenumber',
        ),
    ]
