# Generated by Django 3.0.6 on 2020-05-30 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_size_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.OrderItem'),
        ),
    ]
