# Generated by Django 3.0.6 on 2020-05-30 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_delivery_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='items',
        ),
    ]
