# Generated by Django 3.0.6 on 2020-06-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hd', '0003_auto_20200615_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
                ('email', models.CharField(blank=True, max_length=64)),
                ('phonenumber', models.IntegerField()),
                ('subject', models.CharField(blank=True, max_length=64)),
                ('text', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(blank=True, default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='day',
            name='hour',
            field=models.CharField(default='default', max_length=64),
        ),
    ]
